/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { SaveFeedback$Params } from './fn/feedback/save-feedback';
export { saveFeedback } from './fn/feedback/save-feedback';
export type { FindAllFeedbacksByBook$Params } from './fn/feedback/find-all-feedbacks-by-book';
export { findAllFeedbacksByBook } from './fn/feedback/find-all-feedbacks-by-book';
export type { FindAllBooks$Params } from './fn/book/find-all-books';
export { findAllBooks } from './fn/book/find-all-books';
export type { SaveBook$Params } from './fn/book/save-book';
export { saveBook } from './fn/book/save-book';
export type { UploadBookCoverPicture$Params } from './fn/book/upload-book-cover-picture';
export { uploadBookCoverPicture } from './fn/book/upload-book-cover-picture';
export type { BorrowBook$Params } from './fn/book/borrow-book';
export { borrowBook } from './fn/book/borrow-book';
export type { UpdateShareableStatus$Params } from './fn/book/update-shareable-status';
export { updateShareableStatus } from './fn/book/update-shareable-status';
export type { ReturnBorrowBook$Params } from './fn/book/return-borrow-book';
export { returnBorrowBook } from './fn/book/return-borrow-book';
export type { ApproveReturnBorrowBook$Params } from './fn/book/approve-return-borrow-book';
export { approveReturnBorrowBook } from './fn/book/approve-return-borrow-book';
export type { UpdateArchivedStatus$Params } from './fn/book/update-archived-status';
export { updateArchivedStatus } from './fn/book/update-archived-status';
export type { FindBookById$Params } from './fn/book/find-book-by-id';
export { findBookById } from './fn/book/find-book-by-id';
export type { FindAllReturnedBooks$Params } from './fn/book/find-all-returned-books';
export { findAllReturnedBooks } from './fn/book/find-all-returned-books';
export type { FindAllBooksByOwner$Params } from './fn/book/find-all-books-by-owner';
export { findAllBooksByOwner } from './fn/book/find-all-books-by-owner';
export type { FindAllBorrowedBooks$Params } from './fn/book/find-all-borrowed-books';
export { findAllBorrowedBooks } from './fn/book/find-all-borrowed-books';
export type { Register$Params } from './fn/authentication/register';
export { register } from './fn/authentication/register';
export type { Authenticate$Params } from './fn/authentication/authenticate';
export { authenticate } from './fn/authentication/authenticate';
export type { Confirm$Params } from './fn/authentication/confirm';
export { confirm } from './fn/authentication/confirm';
